### ISSUE TITLE
(Feature Request) Add a temporal `prodrums` instrument for CHOpt

### ISSUE THREAD

**Issue by tposejank** [GenericMadScientist/CHOpt#17]
In the Festival Tracker bot, when a Pro Drums path is generated, the bot will swap all the events in the MIDI from the track `PLASTIC DRUMS` to `PART DRUMS` and then tell CHOpt to use the instrument `drums`. The issue with this is that because the engine is FN Festival, a Pad Drums path will be generated, instead of a proper Pro Drums path. My request here is that there be a temporal replacement for Pro Drums (`prodrums`) and it use an engine like Clone Hero, because otherwise switching the engine only for Pro Drums seems kinda unnecessary, and to avoid switching the MIDI tracks.

Of course, it can be updated once the real Pro Drums comes out.

**Comment by GenericMadScientist** [comment]
What's the motivation for this feature? I fail to see the benefit of drums pathing for an engine that as of yet doesn't exist and nobody can play.

**Comment by tposejank** [comment]
It was due to a request to add a proper Pro Drums path. I personally don't want this, but jnack wanted to see if it was possible.

**Comment by GenericMadScientist** [comment]
Fair, but I'm not going to spend the time adding it to CHOpt until a pro drums mode is released for Fortnite.

If you or jnack want to do the legwork yourself, the easiest way would be a track switch like you're doing and then piece together an engine yourself. The engines are all defined in [engine.hpp](https://github.com/GenericMadScientist/CHOpt/blob/main/include/engine.hpp), and the code that determines the engine class to use is in [settings.cpp](https://github.com/GenericMadScientist/CHOpt/blob/main/src/settings.cpp#L181).

**Comment by tposejank** [comment]
Alright, will note this. Thank you!
