### ISSUE TITLE
(Enhancement) Option to put the Diff in the image. 

### ISSUE THREAD

**Issue by NicoBren** [GenericMadScientist/CHOpt#3]
A good place is: between Chatter name and Score. If Possible. Tks <3

**Comment by GenericMadScientist** [comment]
A good suggestion, and simple enough. However since it affects the layout I'll have to talk with Matref about it so his path scrolling program can handle it, meaning I'll need a little bit before implementing it.

**Comment by NicoBren** [comment]
Another place without messing with the layout directly. It would be in front of the Score like: 

Total Score XXXXXXX - Expert.

**Comment by GenericMadScientist** [comment]
Nah, I don't like the idea of having to fix the layout for the rest of time and it's never a promise I've made. Anyway, we've worked out a system so feature added and it'll be in the next release.
